### ISSUE TITLE
Create Code of Conduct file.md

### ISSUE THREAD

**Issue by ssg8288** [thinktocode/GitFit#7]
your repo didn't had a code of conduct file. Assign this issue to me with relevant tags for both issues and PR's. Thank you

**Comment by thinktocode** [comment]
As you might have seen that someone is already working on the Code of Conduct in issue #2 . You can wait for them to complete and then improve it or pick anything else. I request you see the open issues before creating a new issue.

**Comment by ssg8288** [comment]
> 
> 
> As you might have seen that someone is already working on the Code of Conduct in issue #2 . You can wait for them to complete and then improve it or pick anything else. I request you see the open issues before creating a new issue.

those files have already been created in your pull requests you can check it
